# Generated by Django 4.2.1 on 2023-06-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('thumbnail', models.CharField(max_length=1000)),
                ('series', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Creators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=160)),
            ],
        ),
    ]
