# Generated by Django 4.2.1 on 2023-06-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
