# Generated by Django 4.2.1 on 2023-06-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comic_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creators',
            old_name='title',
            new_name='role',
        ),
        migrations.AddField(
            model_name='creators',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_creators', to='index.comic'),
        ),
    ]
