# Generated by Django 4.2.1 on 2023-06-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rename_title_creators_role_creators_comic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
